### ISSUE TITLE
ID or Reference without a Constraint throws a KeyError

### ISSUE THREAD

**Issue by nealkruis** [bigladder/lattice#20]
See this line here: https://github.com/bigladder/lattice/blob/8795c2caa259bc47c34ee94e951c2d7601715932/lattice/schema_to_json.py#L154

IDs and References need to be able to work without a constrained scope too.

**Comment by tanaya-bigladder** [comment]
I'm not sure I understand - in json, would it then have a `"scopedType": "ID"`, but no associated "scope" tag?

**Comment by tanaya-bigladder** [comment]
Addressed as part of PR #21 .
